### PR TITLE
feat: 🎸 update button background for selected state

### PR DESCRIPTION
**Pull request by ShadowTourist**
Currently just update `CarouseMessageView` cell, I'm not sure if all buttons need be formatted to this style.
|Befor|After|
|-|-|
|Simulator Screen Shot - iPhone 12 Pro - 2021-08-12 at 15 34 44|Simulator Screen Shot - iPhone 12 Pro - 2021-08-12 at 15 13 33|

### CODE REVIEW

**Comment by MarcoEidinger** [comment]
For selected state only 👍 

https://user-images.githubusercontent.com/4176826/129265565-3327b74c-904a-460a-8024-8bc618118802.mp4

**Comment by MarcoEidinger** [comment]
@justinguo is this the behavior for our SDK buttons? Across the board? If yes then button background for selected state should be adopted for all buttons in the CAI iOS SDK, what do you think?

**Comment by justinguo** [comment]
@MarcoEidinger @ShadowTourist Agree. For SAPFiori, all action buttons are using the same tint color and tap state color. So it would be great if we can update this style to all buttons.

**Comment by ShadowTourist** [comment]
There are some strange behavior for expected button style. I'm not sure if it's what you want.
|1|2|3|4|
|-|-|-|-|
|Simulator Screen Shot - iPhone 12 Pro - 2021-08-16 at 15 55 07|Simulator Screen Shot - iPhone 12 Pro - 2021-08-16 at 15 55 28|Simulator Screen Shot - iPhone 12 Pro - 2021-08-16 at 15 55 12|Simulator Screen Shot - iPhone 12 Pro - 2021-08-16 at 15 55 23|

**Pull request closed without merging**
