### PR TITLE
feat: 🎸 expandable plain long text messages with "View more" button

### PR DESCRIPTION
**Pull request by ShadowTourist**
|before|after|
|-|-|
Simulator Screen Shot - iPhone 12 Pro - 2021-09-22 at 08 51 36|Simulator Screen Shot - iPhone 12 Pro - 2021-09-22 at 08 52 14|

### CODE REVIEW

**Review by MarcoEidinger — CHANGES_REQUESTED** [review]
New changes for long text handling are problematic on iOS 15. The scroll view offset is incorrect. Reproducible with Xcode 13 and iOS 15 simulator when checking out PR. Running main branch code with Xcode 13 and iOS 15 then the issue cannot be observed. 

Also please check if long text handling can be applied to texts with markdown formatting.

**Comment by ShadowTourist** [comment]
@MarcoEidinger 
I override below function for iOS seems do not update scrollview content automatically when I expand the truncated message.
So I remove layout constraint and update its size directly.
```swift
override func contentScrollView(for edge: NSDirectionalRectEdge) -> UIScrollView?
```
I also adjust scroll bottom position, because safe area changed when chat view is pushed in iOS 15.(iOS 14 is not)
But, this function seems be called whatever container changes. Like when you scroll it, it will check size continuously.
I'm not sure if it's a good way to make this work. If there is any good idea about this please let me know.

**Comment by MarcoEidinger** [comment]
@ShadowTourist thanks for the update. @justinguo and me will look at this.

@ShadowTourist did you check if truncated text handling can be applied to markdown-styled text?

**Comment by MarcoEidinger** [comment]
Found issue when testing with iOS 13.7 simulator but this can be ignored because I'll bump up minimum deployment target for package and test app to iOS 14 on `dev` branch.

@justinguo will reach out to you to get more context on the solution of updating the hostingControler and scrollView size used in this PR.

But overall looks good and once the build error for Xcode 12.4 is fixed (please apply changes below) I believe the PR is good to be merged. 

 FYI: In the upcoming weeks I'll try to look into replacing `UIScrollViewWrapper` with native SwiftUI components (`ScrollView`, `ScrollViewReader`) and leveraging iOS 14/15 concepts like [keyboard avoidance](https://www.fivestars.blog/articles/swiftui-keyboard/) or [safeAreaInsets()](https://www.fivestars.blog/articles/safe-area-insets-2/) (thanks to bumping up minimum deployment target iOS 14)

**Comment by justinguo** [comment]
@MarcoEidinger FYI, I had a sync-up with @ShadowTourist. The overriding on `contentScrollView()` is to update the size correctly after show more is tapped. Some other alternatives like `layoutIfNeeded()` has been tried but on iOS 15 the size is still incorrect. Unfortunately `contentScrollView()` is a brand new API on iOS 15 and no official documentation. Since there is no better solution, I guess we can go ahead with this implementation at this moment.

**Review by MarcoEidinger — APPROVED** [review]

**Pull request merged**
